# Generated by Django 3.2.9 on 2024-08-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_mailqueue_mailstat_recipelikenotifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailqueue',
            name='mail_type',
            field=models.CharField(choices=[('daily_recipe_like', 'daily_recipe_like')], max_length=20),
        ),
    ]
