# Generated by Django 3.2.9 on 2024-08-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_mailqueue_mail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailstat',
            name='mail_type',
            field=models.CharField(choices=[('daily_recipe_like', 'daily_recipe_like')], max_length=20),
        ),
    ]
